config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  resources :shelters, only: [:index, :new, :create, :edit, :update]

  root "home#index"
  get "about/index"
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :shelter
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  belongs_to :shelter
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :shelter
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
  has_one :meal, autosave: true
  has_one :gender, autosave: true
  has_many :users

  def self.search(search)
    where("name ILIKE ?", "%#{search}%") 
    where("address ILIKE ?", "%#{search}%") 
  end

  accepts_nested_attributes_for :meal, :gender
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  belongs_to :shelter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update]
  before_action :get_shelter, only: [:edit, :update]

  def index
    @shelters = Shelter.all

    if params[:search]
      @shelters = Shelter.search(params[:search]).order("beds ASC")
    else
      @shelters = Shelter.all.order("beds ASC")
    end
  end

  def edit
  end

  def update
    if @shelter.update(shelter_params)
      redirect_to edit_shelter_path(@shelter), notice: "Beds Updated"
    else
      redirect_to edit_shelter_path(@shelter), notice: "Error. Did not update"
    end
  end

  def new
    @shelter = Shelter.new

    @shelter.build_meal
    @shelter.build_gender
  end

  def create
    @shelter = Shelter.create(shelter_params)
    @shelter.users << current_user 

    if @shelter.save
      redirect_to shelters_path, notice: "Created shelter"
    else
      render :new, notice: "Error creating new shelter"
    end
  end

  private

  def get_shelter
    @shelter = current_user.shelter  
  end

  def shelter_params
    params.require(:shelter).permit(:name, 
                                    :description, 
                                    :beds, 
                                    :fee,
                                    :age_min, 
                                    :age_max, 
                                    :phone).tap do |whitelist|
                                      whitelist[:meal] = params[:shelter][:meal]
                                      whitelist[:address] = params[:shelter][:address]
                                      whitelist[:gender] = params[:shelter][:gender]
                                    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<br/>
<br/>
<div class="flex-boxes">
  <span href="javascript:void(0)" class="flex-box flex-box-big">
    <%= fa_icon "home", class: "fa-5x" %>
    <h1 style="font-size:300%" class="flex-title about">About ShelterMatch</h1>
    <h3 style="font-size:150%" class="about">We are dedicated to providing the latest information about shelters in your area.</h3>
    <p class="about">Our service syncs community centers with those in need by making shelter information readily available via our easy to read web app.</p>
  </span>
</div>
<div class="flex-boxes">
  <span href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1_dark.png" alt="">
    <h1 class="flex-title cursive">We make things more simple</h1>
    <p class="cursive">Easily find local centers in your area by using our simple search engine</p>
  </span>
  <span href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1_dark.png" alt="">
    <h1 class="flex-title cursive">Stay informed with up-to date data</h1>
    <p class="cursive">With our service, organizations can provide real time updates for use by the community.</p>
  </span>
</div>
<br/>
<br/>
<br/>

app/views/home/index.html.erb
<article>
  <%= render partial: "refills/welcome_card" %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShelterMatch</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "refills/navigation" %>

    <section>

      <br />
      <%= yield %>

    </section>

    <%= render partial: "refills/footer_2" %>
  </body>
</html>

app/views/refills/_flex_boxes.html.erb
<div class="flex-boxes">
  <a href="javascript:void(0)" class="flex-box flex-box-big">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt="">
    <h1 class="flex-title">A Wide Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad nostrum, libero! Laborum distinctio necessitatibus voluptates eaque officiis, unde illo, earum voluptatum rerum, reiciendis ipsa ex dolorem a dicta, maxime aliquam.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1_dark.png" alt="">
    <h1 class="flex-title">Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum molestiae fugiat tenetur fugit atque dignissimos, fugiat natus vitae.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="">
    <h1 class="flex-title">A Flex Box Item</h1>
    <p>Lorem adipisicing elit. Voluptas consectetur tempora quis nam, officia tenetur blanditiis in illo dolor?</p>
  </a>
  <a href="javascript:void(0)" class="flex-box flex-box-big">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt="">
    <h1 class="flex-title">Another Wide Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae quis ipsum, officia, aperiam tenetur dolor molestiae voluptate perferendis dolorem vel ex, unde fugit blanditiis sapiente.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt="">
    <h1 class="flex-title">Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo obcaecati in provident illo.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="">
    <h1 class="flex-title">Last Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, elit. Rem, illum.</p>
  </a>
</div>

app/views/refills/_footer_2.html.erb
<!--<div class="wrapper-for-content-outside-of-footer">
  Uncomment this whole section for a sticky footer. The content of the page should be inside of this .wrapper-for-content-outside-of-footer
  </div>-->

  <footer class="footer-2" role="contentinfo">
    <div class="footer-logo">
      <%#<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">%>
    </div>
    <ul>
      <%#<li><a href="javascript:void(0)">About</a></li>%>
    </ul>

    <div class="footer-secondary-links">
      <ul>
        <li><%= notice %></li>
        <li><%= alert %></li>
        <li><a href="mailto:chicagoyw@gmail.com?Subject=Hello%20Shelterme!">Contact</a></li>
        <li><a href="mailto:chicagoyw@gmail.com?Subject=Hello%20Shelterme">View Source</a></li>
        <%#<li><a href="javascript:void(0)">Terms and Conditions</a></li>%>
        <%#<li><a href="javascript:void(0)">Privacy Policy</a></li>%>
      </ul>

      <ul class="footer-social">
        <%#<li><a href="https://github.com/clubspark/shelterme">%>
            <%#<%= fa_icon "github", class:"footer-links fa-2x" %>
            <%#</a></li>%>
        <%#<li><a href="javascript:void(0)">%>
            <%#<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">%>
            <%#</a></li>%>
        <%#<li><a href="javascript:void(0)">%>
            <%#<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">%>
            <%#</a></li>%>
        <%#<li><a href="javascript:void(0)">%>
            <%#<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">%>
            <%#</a></li>%>
      </ul>
    </div>
  </footer>

app/views/refills/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <i href="javascript:void(0)" class="logo">
      <%= fa_icon "home", class: "fa-4x" %>
    </i>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><%= link_to "ShelterMatch", root_path, class: "navigation-menu logo-text" %></li>
        <%#<li class="nav-link"><a href="javascript:void(0)">Contact</a></li>%>
        <%#<li class="nav-link more"><a href="javascript:void(0)">More</a>%>
          <%#<ul class="submenu">%>
            <%#<li><a href="javascript:void(0)">Submenu Item</a></li>%>
            <%#<li><a href="javascript:void(0)">Another Item</a></li>%>
            <%#<li class="more"><a href="javascript:void(0)">Item with submenu</a>%>
              <%#<ul class="submenu">%>
                <%#<li><a href="javascript:void(0)">Sub-submenu Item</a></li>%>
                <%#<li><a href="javascript:void(0)">Another Item</a></li>%>
              <%#</ul>%>
            <%#</li>%>
            <%#<li class="more"><a href="javascript:void(0)">Another submenu</a>%>
              <%#<ul class="submenu">%>
                <%#<li><a href="javascript:void(0)">Sub-submenu</a></li>%>
                <%#<li><a href="javascript:void(0)">An Item</a></li>%>
              <%#</ul>%>
            <%#</li>%>
          <%#</ul>%>
        <%#</li>%>
      </ul>
    </nav>
    <div class="navigation-tools">
      <%#<div class="search-bar">%>
        <%#<form role="search">%>
          <%#<input type="search" placeholder="Enter Search" />%>
          <%#<button type="submit">%>
            <%#<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">%>
          <%#</button>%>
        <%#</form>%>
      <%#</div>%>
      <% if user_signed_in? %>
        <%= link_to "edit profile", edit_user_registration_path, class: "sign-up" %>
        <%= link_to "logout", destroy_user_session_path, method: :delete, class: "login" %>
        <% if current_user.shelter_id %>
          <%= link_to "edit shelter", edit_shelter_path(current_user), class: "login" %>
        <% else %>
          <%= link_to "new shelter", new_shelter_path, class: "login" %>
        <% end %>
      <% else %>
        <%= link_to "sign up", new_user_registration_path, class: "sign-up" %>
        <%= link_to "login", new_user_session_path, class: "login" %>
      <% end %>
      <%= link_to "Shelters List", shelters_path, class: "login" %>
    </div>
  </div>
</header>

app/views/refills/_search_bar.html.erb
<%= form_tag(shelters_path, :method => "get", id: "search-form", class: "search-bar") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Chicago" %>
  <button type = "submit">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
  </button>
<% end %>

app/views/refills/_shelter_rows.html.erb
<tr>
  <td><%= shelter.name %></td>
  <td><%= shelter.description %></td>
  <td><%= shelter.beds %></td>
  <td><%if shelter.fee %>None<% else %>Call for info<% end %></td>
  <td><%if shelter.age_min > 0 && shelter.age_max == 0 %>
        <%= shelter.age_min %> and up 
      <% elsif shelter.age_min == 0 && shelter.age_max == 0 %>
        No restrictions
       <% elsif shelter.age_min == 0 && shelter.age_max > 0 %>
         <%= shelter.age_max %> and under 
       <% elsif shelter.age_min > 0 && shelter.age_max > 0 %>
         <%= shelter.age_min %> to <%= shelter.age_max %>
       <% end %></td>
  <td>Female</td>
  <td>Breakfast, Dinner</td>
  <td><%= shelter.phone %></td>
  <td><%= shelter.address %></td>
</tr>

app/views/refills/_shelters_container.html.erb
<button id="fsButton">Fullscreen&nbsp&nbsp<%= fa_icon "arrows-alt" %></button>
<table id="fsContent" class="tables">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Beds</th>
      <th>Fee</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Meals</th>
      <th>Phone</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>
    <% @shelters.each do |shelter| %>
      <%= render partial: "refills/shelter_rows", locals: { shelter: shelter } %>
    <% end %>
  </tbody>
</table>

app/views/refills/_welcome_card.html.erb
<br/>
<br/>
<div class="flex-boxes">
  <span href="javascript:void(0)" class="flex-box flex-box">
    <%= fa_icon "home", class: "fa-5x" %>
    <h1 style="font-size:300%" class="flex-title about">Welcome to ShelterMatch</h1>
    <h3 style="font-size:150%" class="about">We are dedicated to providing the latest information about shelters in your area.</h3>
    <h5 style="font-size:120%" class="about">Start by entering your city below</h5>
      <%= render partial: "refills/search_bar" %>
  </span>
</div>
<br/>
<br/>
<br/>

app/views/shelters/edit.html.erb
<%= form_for @shelter do |f| %>
  <%= f.label :beds %>
  <%= f.number_field :beds %>
  <%= f.submit "Update Shelter" %>
<% end %>

app/views/shelters/index.html.erb
<article>
  <%= render partial: "refills/shelters_container" %>
</article>

app/views/shelters/new.html.erb
<article>
  <div class="cards">
    <div class="card">
      <div class="card-copy">
        <%= form_for @shelter do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>

          <%= f.label :description %>
          <%= f.text_field :description %>

          <%= f.label :beds %>
          <%= f.number_field :beds %>

          <%= f.label :fee %>
          <%= f.check_box :fee %><br>

          <%= f.label :age_min %>
          <%= f.number_field :age_min %>

          <%= f.label :age_max %>
          <%= f.number_field :age_max %>

          <ul>
          <%= f.fields_for :gender_id do |gender| %>
            <%= gender.label :male %>
            <%= gender.check_box :male %>
            <%= gender.label :female %>
            <%= gender.check_box :female %>
            <%= gender.label :other %>
            <%= gender.check_box :other %>
          <% end %>
          </ul>

          <ul>
          <%= f.fields_for :meal_id do |meal| %>
            <%= meal.label :breakfast %>
            <%= meal.check_box :breakfast %>
            <%= meal.label :lunch %>
            <%= meal.check_box :lunch %>
            <%= meal.label :dinner %>
            <%= meal.check_box :dinner %>
          <% end %>
          </ul>

          <%= f.label :phone %>
          <%= f.telephone_field :phone %>

          <%= f.label :address %>
          <%= f.text_field :address %>

          <%= f.submit "Create Shelter" %>
        <% end %>
      </div>
    </div>
  </div>
  <br />
  <br />
  <br />
<article>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>